name: Mihomo Rules Auto-Build
on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    runs-on: ubuntu-latest
    # 赋予推送权限
    permissions:
      contents: write
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
        with:
          ref: program

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests

      - name: Run Merge Script
        run: python scripts/merge.py

      - name: Setup Mihomo
        run: |
          URL=$(curl -s https://api.github.com/repos/MetaCubeX/mihomo/releases/latest | grep "browser_download_url.*linux-amd64-v" | cut -d '"' -f 4 | head -n 1)
          curl -L -o mihomo.gz "$URL"
          gunzip mihomo.gz && chmod +x mihomo

      - name: Prepare Deployment Directory
        run: |
          mkdir -p deploy/mrs
          mkdir -p deploy/raw

      - name: Compile and Copy
        run: |
          for file in source/*.list; do
            filename=$(basename "$file" .list)
            [ -f "source/${filename}.type" ] && ptype=$(cat "source/${filename}.type") || ptype="domain"
            ./mihomo convert-ruleset "$ptype" text "$file" "deploy/mrs/${filename}.mrs"
            cp "$file" "deploy/raw/${filename}.txt"
          done

      # 时间修复方案
      - name: Get current date
        id: get_date
        run: echo "today=$(TZ='Asia/Shanghai' date +'%Y-%m-%d %H:%M')" >> $GITHUB_OUTPUT

      - name: Deploy to Release Branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: release
          publish_dir: ./deploy
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          # 使用 outputs 引用时间
          commit_message: "Auto-build rules at ${{ steps.get_date.outputs.today }}"
          keep_files: false
